TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# In a Diamond Support Module, install
# templates like this
#
DB += ffmpegStream.template
DB += ffmpegFile.template

ARCHIVE += ffmpegStream.tpl-arch
ARCHIVE += ffmpegFile.tpl-arch

REQ += ffmpegStream.tpl-req
REQ += ffmpegFile.tpl-req

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
