#!/bin/sh
# This file was automatically generated on Mon 28 May 2012 18:31:37 BST from
# source: /dls_sw/prod/R3.14.11/support/ffmpegServer/1-9/etc/makeIocs/example_win32.xml
# 
# *** Please do not edit this file: edit the source file instead. ***
# 
cd "$(dirname "$0")"
if [ -n "$1" ]; then
    export EPICS_CA_SERVER_PORT="$(($1))"
    export EPICS_CA_REPEATER_PORT="$(($1 + 1))"
    [ $EPICS_CA_SERVER_PORT -gt 0 ] || {
        echo "First argument '$1' should be a integer greater than 0"
        exit 1
    }
fi
exec ./example_win32 stexample_win32.boot
