/* This file was automatically generated on Fri 14 Jun 2013 14:12:59 BST from
 * source: /dls_sw/prod/R3.14.11/support/ffmpegServer/1-16-3/etc/makeIocs/example_win32.xml
 * 
 * *** Please do not edit this file: edit the source file instead. ***
 *  */
#include "epicsExit.h"
#include "epicsThread.h"
#include "iocsh.h"

int main(int argc, char *argv[])
{
    if(argc>=2) {
        iocsh(argv[1]);
        epicsThreadSleep(.2);
    }
    iocsh(NULL);
    epicsExit(0);
    return 0;
}

